[tool.poetry]
name = "nitinpython"
version = "0.1.0"
description = "A project that generates random poems using Python."

[tool.poetry.dependencies]
python = "^3.8"
random = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
